### ISSUE TITLE
Not compatible with data from 'xlsx' package

### ISSUE THREAD

**Issue by wangjz1984** [helixcn/spaa#1]
I loaded data in a xlsx file with 'xlsx' package, and then tried to convert data format with 'data2mat' for calculating diversity index. But there was an error report: Number of individuals must be integer! Is it a bug? I'm sure the number of individuals is integer. 
It didn't occur, if I loaded data in csv files.

Original data format is as followed:
plotname  species  abundance
1                name1    123
2                name2     23
...

**Comment by helixcn** [comment]
Sorry for delay in response.
Thanks for your comments. I will look at this issue.
Happy New Year!
Cheers,

Jinlong

Jinlong Zhang, PhD
Flora Conservation Department,
Kadoorie Farm and Botanic Garden (KFBG),
Lam Kam Road, Tai Po, New Territories,
Hong Kong SAR, China
http://jinlongzhang.weebly.com/
